import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import type { MissionBrief } from "@iceberg/parser";

export interface HandoverFile {
  path: string;
  content: string;
}

export interface HandoverOptions {
  templateId: string;
  assumptionBased?: boolean;
}

export function generateHandoverPackage(brief: MissionBrief, options: HandoverOptions): HandoverFile[] {
  const envNames = inferEnvNames(brief, options.templateId);
  const banner = options.assumptionBased
    ? "> ASSUMPTION-BASED PLAN: generated from the M5 plan because the checked-in mission brief is known to be wrong.\n\n"
    : "";

  return [
    {
      path: "README.md",
      content: `${banner}# ${titleize(brief.mission_id)}\n\nGenerated by Iceberg Agent Stack. Human review is required before merge or production use.\n\n## Problem\n${brief.problem}\n\n## Quick Start\n1. Install Node.js 20+.\n2. Run \`npm install\`.\n3. Copy \`.env.example\` to \`.env\` and fill values locally.\n4. Run \`npm run dev\`.\n\n## Deliverables\n${list(brief.deliverables)}\n\n## Constraints\n${list(brief.constraints)}\n\n## Template\n\`${options.templateId}\`\n`
    },
    {
      path: "TEST_PLAN.md",
      content: `# TEST_PLAN\n\n## Automated\n- Unit: parser and service helpers\n- API: happy path plus one error path per public endpoint\n- Integration: one end-to-end mock flow\n- CI: \`npm run lint && npm run typecheck && npm run test -- --coverage\`\n\n## Manual Demo\n- Parse the mission brief and confirm structured JSON.\n- Run scaffold in dry-run mode and confirm no files are written.\n- Run scaffold with human approval and inspect generated tree.\n- Confirm \`.env.example\` contains names only, no secret values.\n\n## Security\n- Secret files such as \`.env\`, private keys, and credentials are not read by the agent.\n- Generated output must be reviewed by a human before merge.\n`
    },
    {
      path: "HANDOVER.md",
      content: `${banner}# HANDOVER\n\n## Summary\nThis scaffold was generated from a structured mission brief using the \`${options.templateId}\` template.\n\n## Generated Scope\n${list(brief.deliverables)}\n\n## Known Issues\n- This is a POC scaffold, not production-ready code.\n- LLM integration is optional; deterministic rule-based generation must remain functional.\n- Any external API credentials must be supplied by humans outside agent context.\n\n## Next Steps\n- Review generated files and remove unused placeholders.\n- Add mission-specific endpoint tests.\n- Confirm CI is green before demo submit.\n\n## Governance\n- AI-generated output requires human review.\n- No autonomous push, merge, or production deploy.\n- Secrets are represented only by environment variable names.\n`
    },
    {
      path: ".env.example",
      content: `${envNames.map((name) => `${name}=YOUR_${name}_HERE`).join("\n")}\n`
    }
  ];
}

export async function writeHandoverPackage(files: HandoverFile[], outputDir: string): Promise<void> {
  for (const file of files) {
    const target = path.join(outputDir, file.path);
    await mkdir(path.dirname(target), { recursive: true });
    await writeFile(target, file.content, "utf8");
  }
}

export function inferEnvNames(brief: MissionBrief, templateId: string): string[] {
  const names = new Set(["NODE_ENV", "LLM_PROVIDER", "LLM_MODEL"]);
  if (templateId === "api-integration-core") {
    names.add("MOCK_API");
    names.add("API_BASE_URL");
    names.add("API_CLIENT_ID");
    names.add("API_CLIENT_SECRET");
    names.add("WEBHOOK_SECRET");
  }
  if (templateId === "crm-mock-poc") {
    names.add("CRM_MODE");
    names.add("CRM_API_BASE_URL");
  }
  if (templateId === "intelligence-layer") {
    names.add("GEMINI_API_KEY");
    names.add("OPENAI_API_KEY");
    names.add("ANTHROPIC_API_KEY");
  }
  if (/cursor/i.test([...brief.tech_hints ?? [], brief.problem].join(" "))) {
    names.add("CURSOR_API_KEY");
  }
  return [...names].sort();
}

function list(values: string[]): string {
  return values.map((value) => `- ${value}`).join("\n");
}

function titleize(value: string): string {
  return value.replace(/-/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
}
